import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import 'normalize.css/normalize.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-background-color text-white min-h-screen">
        {children}
      </body>
    </html>
  );
}
